name: deploy-backend-euaiact

on:
  push:
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::155574108262:role/AWSReservedSSO_AdministratorAccess_b23e7ac0552e2f2d
          aws-region: eu-north-1

      - name: Install
        run: npm ci

      - name: Deploy (dev)
        run: npx serverless deploy --stage dev --region eu-north-1
